config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "books#index"

  resources :books do
    member do
      get :delete
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.order(:title)
  end
  
  def show
    @book = Book.find(params[:id])
  end
  
  def new
    # @count = Book.count()
    @book = Book.new()
  end
  
  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path, notice: "New book has been added to the collection!"
    else
      # the 'new' action A is not being called here
      # assign any instance variables needed
      render('new')
    end
  end
  
  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    redirect_to book_path(@book), notice: "Book has been edited!"
    else
      render('edit')
    end
  end
  
  def delete
    @book = Book.find(params[:id])
  end

  # function for destroying a book from collection
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: "Book has been deleted from the collection!"
  end
  
  private
  
  def book_params
    params.required(:book).permit(
      :title,
      :author,
      :price,
      :published
    )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
    <table summary="Book form fields">
      <tr>
        <th>Title</th>
        <td><%= f.text_field(:title) %></td>
      </tr>
      <tr>
        <th>Author</th>
        <td><%= f.text_field(:author) %></td>
      </tr>
      <tr>
        <th>Price</th>
        <td><%= f.text_field(:price) %></td>
      </tr>
      <tr>
        <th>Publish Date</th>
        <td><%= f.text_area(:published) %></td>
      </tr>
    </table>

app/views/books/delete.html.erb
<%= link_to("Back to Home", books_path, class: 'back-link') %>

<div class="books delete">
  <h2>Delete Book</h2>

  <%= form_for(@book, method: 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this book?</p>
    <p><%= @book.title %></p>

    <div class="form-buttons">
      <%= f.submit("Delete book") %>
    </div>

  <% end %>
</div>

app/views/books/edit.html.erb
<%= link_to("Back to Home", books_path, :class => 'back-link') %>

<div class="books edit">
  <h2>Edit Book</h2>

  <%= form_for(@book) do |f| %>

    <%= render(partial: 'form', locals: {f: f}) %>

    <div class="form-buttons">
      <%= f.submit("Edit Book") %>
    </div>

  <% end %>
</div>

app/views/books/index.html.erb
<!-- <%= link_to('Back to Homepage', {controller: 'books', action: 'index'}) %><br /> -->

<div class="books index">
  <h2>Book Collection</h2>

  <%= link_to("Add New Book", new_book_path, class: 'action new') %>

  <% flash.each do |type, msg| %>
    <div>
      <%= msg %>
    </div>
  <% end %>

  <table class="listing" summary="Book list" style="width: 100%;">
    <tr class="header">
      <th>Title</th>
      <th>Author</th>
      <th>Price</th>
      <th>Publish Date</th>
    </tr>
    <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.author %></td>
      <td><%= book.price %></td>
      <td><%= book.published %></td>
      <td class="actions">
        <%= link_to("Show", book_path(book), class: 'action show') %>
        <%= link_to("Edit", edit_book_path(book), class: 'action edit') %>
        <%= link_to("Delete", delete_book_path(book), class: 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/books/new.html.erb
<%= link_to("Back to Home", books_path, :class => 'back-link') %>

<div class="books new">
  <h2>Create Book</h2>

  <%= form_for(@book) do |f| %>

    <%= render(partial: 'form', locals: {f: f}) %>

    <p>Date in format yyyy-mm-dd</p>

    <div class="form-buttons">
      <%= f.submit("Create Book") %>
    </div>

  <% end %>
</div>

app/views/books/show.html.erb
<%= link_to("Back to Home", books_path, class: 'back-link') %>

<div class="books show">
  <h2>Show book</h2>

  <div class="actions">
    <%= link_to('Edit', edit_book_path(@book)) %>
    <%= link_to('Delete', delete_book_path(@book)) %>
  </div>

  <table summary="Book detail view">
    <tr>
      <th>Title</th>
      <td><%= @book.title %></td>
    </tr>
    <tr>
      <th>Author</th>
      <td><%= @book.author %></td>
    </tr>
    <tr>
      <th>Price</th>
      <td><%= @book.price %></td>
    </tr>
    <tr>
      <th>Publish Date</th>
      <td><%= @book.published %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @book.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @book.updated_at %></td>
    </tr>
  </table>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book Collection</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>